FoodDeliveryApp/FoodDeliveryApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodDeliveryApp.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

FoodDeliveryApp/FoodDeliveryApp/Controllers/OrderController.cs
using AutoMapper;
using FoodDeliveryApp.Auth;
using FoodDeliveryApp.EF;
using FoodDeliveryApp.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodDeliveryApp.Controllers
{
    public class OrderController : Controller
    {
        FoodDeliveryAppEntities db = new FoodDeliveryAppEntities();
        // GET: Order
        [LoggedIn]
        public ActionResult Index()
        {
            return View();
        }

        [UserAccess]
        public ActionResult AddToCart(int id)
        {
            var food = db.Foods.Find(id);
            var config = new MapperConfiguration(cfg => {
                cfg.CreateMap<Food, FoodDTO>();
            });
            var mapper = new Mapper(config);
            var fd = mapper.Map<FoodDTO>(food);
            if (Session["Cart"] == null)
            {
                var cart = new List<FoodDTO>();
                cart.Add(fd);
                Session["Cart"] = cart;
            }
            else
            {
                var cart = (List<FoodDTO>)Session["Cart"];
                cart.Add(fd);
                Session["Cart"] = cart;
            }
            TempData["Msg"] = food.FName + " added to cart successfully";
            return RedirectToAction("ResturantMenu", "Resturant", new { id = food.RId });
        }

        [UserAccess]
        public ActionResult Cart()
        {
            var cart = (List<FoodDTO>)Session["Cart"];
            if(cart == null)
            {
                TempData["Msg"] = "Cart is empty";
                return RedirectToAction("Index", "User");
            }
            return View(cart);
        }

        [UserAccess]
        public ActionResult PlaceOrder(decimal total, int rid)
        {
            var order = new Order();
            order.UId = ((User)Session["UserData"]).Id;
            order.RId = rid;
            order.DateTime = DateTime.Now;
            order.Status = "Placed";
            order.TotalAmount = total;
            db.Orders.Add(order);
            db.SaveChanges();

            var cart = (List<FoodDTO>)Session["Cart"];
            foreach (var item in cart)
            {
                var orderFood = new OrderFood();
                orderFood.FId = item.Id;
                orderFood.OId = order.Id;
                orderFood.FPrice = item.FPrice;
                orderFood.FQty = 1;
                db.OrderFoods.Add(orderFood);
                db.SaveChanges();
            }
            Session["Cart"] = null;
            TempData["Msg"] = "Order placed successfully";
            return RedirectToAction("Index", "User");
        }

        [UserAccess]
        public ActionResult RemoveFromCart(int id)
        {
            var cart = (List<FoodDTO>)Session["Cart"];
            var item = cart.FirstOrDefault(x => x.Id == id);
            cart.Remove(item);
            if (cart == null)
            {
                TempData["Msg"] = item.FName + " removed from cart successfully and cart is empty!";
                return RedirectToAction("Index", "User");
            }
            Session["Cart"] = cart;
            TempData["Msg"] = item.FName + " removed from cart successfully";
            return RedirectToAction("Cart");
        }
    }
}

FoodDeliveryApp/FoodDeliveryApp/Controllers/UserController.cs
using AutoMapper;
using FoodDeliveryApp.Auth;
using FoodDeliveryApp.DTOs;
using FoodDeliveryApp.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodDeliveryApp.Controllers
{
    [UserAccess]
    public class UserController : Controller
    {
        FoodDeliveryAppEntities db = new FoodDeliveryAppEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SignUp(UserDTO u)
        {
            if (ModelState.IsValid)
            {
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.CreateMap<UserDTO, User>();
                });
                var mapper = new Mapper(config);
                var data = mapper.Map<UserDTO, User>(u);
                data.Name = u.FirstName.Trim() + " " + u.LastName.Trim();
                db.Users.Add(data);
                TempData["Msg"] = "User Registered Successfully";
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(u);
        }
    }
}

FoodDeliveryApp/FoodDeliveryApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Delivery App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("FoodApp", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Resturants", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Orders", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li><a class="btn btn-danger" href="/Login/Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FoodApp - Food Delivery App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FoodDeliveryApp/FoodDeliveryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Delivery App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("FoodApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FoodApp - Food Delivery App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FoodDeliveryApp/FoodDeliveryApp/Views/Shared/_ResturantLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Delivery App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("FoodApp", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Menu", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Current Orders", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Previous Orders", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li><a class="btn btn-danger" href="/Login/Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FoodApp - Food Delivery App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FoodDeliveryApp/FoodDeliveryApp/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Delivery App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("FoodApp", "Index", "User", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Resturants", "ResturantsList", "Resturant", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Cart", "Cart", "Order", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Current Order", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Previous Orders", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li><a class="btn btn-danger" href="/Login/Logout">Logout</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FoodApp - Food Delivery App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>